USE tienda_organica_db;

INSERT INTO `categories` 
VALUES (1,"frutas",null,null),(2,"verduras",null,null),(3,"canastas",null,null);

INSERT INTO `products` 
VALUES (1,"Manzana roja","La manzana es el fruto ideal para tomar a cualquier hora y participa positivamente en la consecución del equilibrio alimentario. A la manzana se le atribuyen muchas propiedades curativas, aparte de su reconocido poder diurético. Como su nombre indica, tiene una piel roja oscura con un dulzor medio, entre la manzana golden y la manzana verde. Es aromática y tiene una carne jugosa. Este tipo de manzanas es el más utilizado para acompañar las ensaladas.","1kg",240,80,1,"manzana-roja.png",1,null,null),
(2,"Manzana verde","La manzana es el fruto ideal para tomar a cualquier hora y participa positivamente en la consecución del equilibrio alimentario. A la manzana se le atribuyen muchas propiedades curativas, aparte de su reconocido poder diurético. Como su nombre indica, tiene una piel roja oscura con un dulzor medio, entre la manzana golden y la manzana verde. Es aromática y tiene una carne jugosa. Este tipo de manzanas es el más utilizado para acompañar las ensaladas.","1kg",250,60,0,"manzana-verde.png",1,null,null),
(3,"Mandarina","Esta fruta cítrica y típica de otoño es deliciosa y refrescante.","1kg",100,70,0,"mandarina.png",1,null,null),
(4,"Pomelo rosado","El pomelo se consume principalmente como fruta fresca, y posee numerosas cualidades digestivas, estomacales y antisépticas. Previene las enfermedades cardiovasculares, fortalece el sistema inmunológico, previene los resfriados, estabiliza la flora intestinal, activa el metabolismo y el crecimiento celular, y contribuye a la pérdida de peso. La vitamina C y los beta-carotenos presentes en cantidades elevadas en el zumo de esta fruta actúan como antioxidantes.","1kg",180,40,0,"pomelo.png",1,null,null),
(5,"Banana","El plátano es una fruta amarilla con un sabor dulce según la variedad. Se pueden distinguir algunas variedades por su diferencia de tamaño, color, sabor más o menos dulce y su forma de consumo. Es rico en fibra, potasio y algunas vitaminas beneficiosas para la salud. Es una fruta buena para todos excepto diabéticos y obesos, debido a su alto contenido en almidón y azúcares. Además esta fruta es una buena fuente de energía, de vitamina A y potasio.","1kg",180,90,0,"banana.png",1,null,null),
(6,"Frutilla","La frutilla es un fruto de color rojo brillante, suculento y fragante. Las fresas y los fresones son poco calóricos y aportan un sabor dulce y agradable. Después del agua, su principal constituyente son los hidratos de carbono. La fructosa significa prácticamente la mitad de sus glúcidos y el resto es glucosa en su mayor parte. Es adecuada en régimenes dietéticos, dado que tiene escasa concentración de glúcidos. Constituye una excelente fuente de vitamina C.","250gr",500,48,1,"frutilla.png",1,null,null),
(7,"Limón","El limón refuerza el sistema inmunológico, es revitalizante, activa el metabolismo del calcio para los huesos y dientes, cura las hemorragias, tiene acción rejuvenecedora y ayuda en las dietas de adelgazamiento. Se consume en fresco en el terreno gastronómico, su uso está más aplicado como zumo en condimentos para sopas, bebidas, ensaladas, platos de pescado y postres de pastelería. Tiene un elevado contenido en vitaminas A, B, P, K y sobre todo C.","1kg",60,15,0,"limon.png",1,null,null),
(8,"Naranja","La naranja, junto con el plátano y la manzana, es uno de los frutos más consumidos en el mundo. La parte comestible de la naranja es la pulpa y se consume fresca o en zumo. La naranja también se utiliza para realizar compotas, mermeladas, para consumo como fruta deshidratada, etc. Las naranjas frescas son bajas en calorías y fuente de fibra, potasio, vitamina C y folato. Ayudan a prevenir el cáncer y las enfermedades cardiovasculares.","1kg",120,124,0,"naranja.png",1,null,null),
(9,"Palta","Excelente fuente de grasas saludables, especialmente ácidos grasos omega 9. Alta en fibra: brindando alto nivel de saciedad, equilibrando niveles de azúcares en sangre y regulando el tránsito intestinal.","1 unidad",85,40,0,"palta.png",1,null,null),
(10,"Uva verde","La uva verde es un fruta que crece en racimos apretados. Su pulpa es blanca de sabor dulce. Se consume como fruta fresca o zumo. Las uvas son un alimento que aporta minerales y vitaminas al organismo. Es una de las frutas con más hidratos de carbono, aunque su contenido calórico no es demasiado elevado. Contienen resveratrol, un compuesto antioxidante y anticancerígeno, y desde la antigüedad se le atribuyen diversas propiedades curativas.","500gr",380,82,1,"uva-verde.png",1,null,null),
(11,"Acelga","La acelga es una planta con grandes hojas verdes y carnosas pencas blancas. La acelga goza de numerosas aplicaciones medicinales y alimenticias. En ensalada con zumo de limón fortalece el estómago y vigoriza el cerebro, así como desinflama los nervios. Las hojas de las acelgas aportan una gran cantidad de calcio además de la vitamina K. Se consume normalmente cocida y aderezada como hervido, o bien como acompañante.","1 atado",90,22,0,"acelga.png",2,null,null),
(12,"Brócoli","El brócoli es una hortaliza de la familia de las coles. Tiene un agradable sabor. Es un alimento rico en vitaminas, sobre todo en vitamina C y vitamina A. Contiene fibra, calcio, hierro y potasio. Además es bajo en calorías y grasas, por lo que es recomendable en dietas de adelgazamiento. El consumo de brócoli puede ayudar a aquellas personas que padecen estrés o nervios. Se consume crudo, especialmente el tronco pelado, tanto como al vapor o hervido.","1 unidad",340,12,1,"brocoli.png",2,null,null),
(13,"Batata","Se trata de una raíz que se obtiene de la planta que recibe el nombre de batata. Su sabor es dulce debido a su contenido en azúcares. La batata recuerda a la patata aunque botánicamente no está emparentado con ella. Por su combinación de nutrientes y su riqueza en hidratos de carbono se puede decir que es un alimento regenerador y de alto valor energético. Posee una gran concentración de vitamina A. También tiene gran proporción en vitamina E, C y ácido fólico.","1kg",55,43,1,"batata.png",2,null,null),
(14,"Berenjena","La berenjena es un fruto de color morado. Su carne firme y suave es siempre blanca y contiene numerosas semillas comestibles del mismo color. La berenjena es muy saludable. Es un alimento bajo en calorías y en hidratos de carbono. Es de muy fácil digestión y contiene una buena cantidad de zinc y potasio. Presenta en su mayor parte vitaminas A, C y ácido fólico. Se consume a modo de verdura, frita o rebozada en rodajas.","1kg",145,13,0,"berenjena.png",2,null,null),
(15,"Cebolla","La cebolla es el bulbo subterráneo y comestible que crece en la planta del mismo nombre. La cebolla ha sido usada desde hace mucho tiempo como planta medicinal, por lo que existen muchas recetas y remedios para combatir diversas dolencias y patologías. Su riqueza en minerales y vitaminas es relativamente baja, pero es rica en aceites esenciales que contienen azufre. La cebolla se consume cruda, frita, hervida y asada, casi siempre como condimento.","1kg",80,43,0,"cebolla.png",2,null,null),
(16,"Papa","La papa es un tubérculo, redondeado u ovalado con unos pequeñas raicillas blancas llamadas ojos que no son más que yemas de crecimiento. Es uno de los cultivos más extendidos en todo el mundo. Es una buena fuente de energía, con alto contenido en folato, vitamina C, vitaminas del grupo B, hierro y potasio. Es peligroso consumir papas color verdoso porque contienen un compuesto que en grandes cantidades puede ser tóxico.","1kg",115,88,1,"papa.png",2,null,null),
(17,"Morrón rojo","El morrón rojo es más dulce que el morrón verde y amarillo. Tiene un alto contenido en vitaminas y antioxidantes y representa un poderoso alimento que combate el envejecimiento y varias enfermedades graves. La principal vitamina aportada por los pimientos es la vitamina C que protege contra el cáncer. También es fuente de vitamina A, por lo que son buenos para la vista. El morrón se consume crudo, cocido y asado o como guarnición en gran variedad de platos.","1 unidad",330,37,0,"morron-rojo.png",2,null,null),
(18,"Tomate perita","El tomate perita es una variedad de tomate grande con pulpa carnosa, poco ácida, de forma oblonga, aplanada, con protuberancias en la superficie. Es el preferido para la elaboración de los tomates en conserva. También es uno de los tomates de verano más apreciados para la elaboración del refrescante y nutritivo gazpacho y salmorejo. Sus cualidades también lo convierten en el tomate ideal para hacer tomate frito, para comer en ensalada y para untar en el pan.","1kg",170,8,0,"tomate-perita.png",2,null,null),
(19,"Lechuga","La lechuga es una hortaliza muy popular que se cultiva por sus grandes hojas. La lechuga criolla es una variedad de lechuga que crece con una larga cabeza y que posee una hojas robustas, alargadas y con un robusto nervio central. Es un alimento pobre en nutrientes, con muy poco contenido graso, lo que la hace indicada para dietas de adelgazamiento. Se le atribuyen propiedades calmantes y sedantes. Además combate el estreñimiento y el agotamiento, es diurética.","500gr",150,17,1,"lechuga.png",2,null,null),
(20,"Zanahoria","La zanahoria es una hortalizas muy extendida. La parte de la planta que se consume es la raíz, de la que existen diferentes variedades, de modo que el sabor y la forma pueden variar, aunque siempre con coloración anaranjada. Es rica en caroteno, sustancia precursora de la vitamina A, necesaria en el crecimiento, desarrollo de huesos, vista, mantenimiento de los tejidos, reproducción y en el sistema hormonal. Además, se cree que previene contra el cáncer.","1kg",60,22,0,"zanahoria.png",2,null,null),
(21,"Calabaza anco","La calabaza es uno de esos alimentos excepcionales a los que todavía no se ha hecho debida justicia. Su pulpa es generalmente anaranjada o amarillenta, y está repleta de semillas en su parte central. Es digestiva, deliciosa, de aspecto atractivo y está repleta de sustancias con efectos muy beneficiosos sobre la salud. La carne de la calabaza se consume cocinada como verdura, cocida, frita, gratinada, acompañada de salsas y como guarnición de diversos platos.","1 unidad",125,16,0,"calabaza-anco.png",2,null,null),
(22,"Coliflor","La coliflor es una hortaliza perteneciente a la familia de las coles. La parte que se consume es la flor o inflorescencia, muy apreciada por su sabor. Se puede utilizar de distintas maneras, tanto cruda como cocinada. La coliflor es adecuada en dietas de adelgazamiento, ya que es un alimento bajo en calorías y rico en fibra. Aporta muchas vitaminas y minerales, por lo que resulta beneficiosa en enfermedades circulatorias y cardiacas y la prevención de algunos cánceres.","1 unidad",160,7,0,"coliflor.png",2,null,null),
(23,"Canasta de frutas","Ahorrá disfrutando de nuestra selección de fruta de proximidad. Nuestra caja de 6kg es ideal para 2 personas.","1 unidad",800,45,0,"canasta-de-frutas.jpg",3,null,null),
(24,"Canasta de verduras","Disfrutá de nuestras selección de verduras de proximidad. Nuestra cesta de verdura de 6kg es ideal para 2 personas.","1 unidad",600,38,0,"canasta-de-verduras.jpg",3,null,null),
(25,"Canasta familiar","Ahorrá disfrutando de nuestra selección de fruta y verdura de proximidad. Nuestra caja de 15kg es ideal para 4 o 5 personas","1 unidad",1500,62,1,"canasta-familiar.jpg",3,null,null);

INSERT INTO `roles` 
VALUES (1,"Admin",null,null),(2,"User",null,null);

INSERT INTO `users` 
VALUES (1,"Admin","User","admin@test.com","$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q",12345678,"default.jpg",1,null,null),
(2,"Valeria","Ibañez","valeibanez21@gmail.com","$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q",12345678,"vale.jpg",1,null,null),
(3,"Mariano","Baliño","marian@gmail.com","$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q",12345678,"marian.jpg",1,null,null),
(4,"David","Leal","davidleal@gmail.com","$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q",12345678,"david.jpg",1,null,null),
(5, "Basil", "McGuggy", "bmcguggy4@xing.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 6882141469, "5.jpg", 2, null, null),
(6, "Aguistin", "Clardge", "aclardge5@booking.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 1243743884, "6.jpg", 2, null, null),
(7, "Parke", "Fitzroy", "pfitzroy6@creativecommons.org", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 5078412849, "7.jpg", 2, null, null),
(8, "Rufe", "Davisson", "rdavisson7@java.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 7376474424, "8.jpg", 2, null, null),
(9, "Domenico", "Crossthwaite", "dcrossthwaite8@foxnews.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 5992016960, "9.jpg", 2, null, null),
(10, "Robert", "Coyte", "rcoyte9@pen.io", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 4566074370, "10.jpg", 2, null, null),
(11, "Alisha", "Adan", "aadana@newsvine.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 1509684993, "11.jpg", 2, null, null),
(12, "Tremain", "Hercock", "thercockb@tmall.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 7561815352, "12.jpg", 2, null, null),
(13, "Gregory", "Senussi", "gsenussic@pen.io", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 4789918346, "13.jpg", 2, null, null),
(14, "Artur", "Graddell", "agraddelld@chron.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 3757337724, "14.jpg", 2, null, null),
(15, "Rowan", "Blanche", "rblanchee@cnet.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 2669968012, "15.jpg", 2, null, null),
(16, "Roldan", "Finker", "rfinkerf@prweb.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 3144038831, "16.jpg", 2, null, null),
(17, "Zonnya", "Camilleri", "zcamillerig@nih.gov", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 3774329047, "17.jpg", 2, null, null),
(18, "Karena", "Haggart", "khaggarth@naver.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 2606235803, "18.jpg", 2, null, null),
(19, "Gianni", "Entreis", "gentreisi@elpais.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 3672390928, "19.jpg", 2, null, null),
(20, "Adora", "Dach", "adachj@indiatimes.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 7739802642, "20.jpg", 2, null, null),
(21, "Galina", "Wooland", "gwoolandk@europa.eu", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 6147772793, "21.jpg", 2, null, null),
(22, "Kerby", "Alenshev", "kalenshevl@alibaba.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 9645119233, "22.jpg", 2, null, null),
(23, "Artie", "Allbon", "aallbonm@google.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 5499118365, "23.jpg", 2, null, null),
(24, "Rosette", "Petriello", "rpetriellon@ed.gov", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 3316222266, "24.jpg", 2, null, null),
(25, "Nathalie", "Dewhurst", "ndewhurst0@blogs.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 9067890652, "25.jpg", 2, null, null),
(26, "Lynn", "Starmer", "lstarmer1@php.net", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 2901027054, "2.jpg", 2, null, null),
(27, "Yvon", "Cowgill", "ycowgill2@taobao.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 9283053134, "3.jpg", 2, null, null),
(28, "Bondy", "Duffrie", "bduffrie3@gravatar.com", "$2a$10$VisC9Rx68RbPKM1vMAigNe0S6BsvZQoYMYuaJPAwrTkdpaLE/mQ9q", 8646047253, "4.jpg", 2, null, null);

INSERT INTO `addresses` 
VALUES (1,"Calle Falsa 123",3000,"CABA","Buenos Aires",1,"","");